name = "hugo-theme-tokyo-terminal"
license = "MIT"
licenselink = "https://github.com/rehan-hk/hugo-tokyo-night-terminal-theme/blob/main/LICENSE"
description = "A terminal-style Hugo theme with Tokyo Night color scheme and JetBrains Mono."
homepage = "https://github.com/rehan-hk/hugo-tokyo-night-terminal-theme"
tags = ["minimal", "terminal", "dark", "tokyo-night"]
features = ["blog", "portfolio", "cv"]
min_version = "0.90.0"

[author]
  name = "Mohd Rehan Haider Kazmi"
  homepage = "https://rehan-hk.dev"

[module]
  [module.hugoVersion]
    min = "0.90.0"
